# Generated by Django 5.2.13 on 2026-04-27 10:18

import json
import uuid
from pathlib import Path                                                                                                                  
from django.db import migrations
                                                                                                                                            
SPATIAL_VIEWS_DIR = Path(__file__).parent / "spatial_views"

def create_spatial_views(apps, schema_editor):
  SpatialView = apps.get_model("models", "SpatialView")
  Node = apps.get_model("models", "Node")                                                                                               
  Language = apps.get_model("models", "Language")
                                                                                                                                            
  language = Language.objects.get(isdefault=True)

  for path in SPATIAL_VIEWS_DIR.glob("*.json"):                                                                                         
      view = json.loads(path.read_text())
      SpatialView.objects.create(                                                                                                       
          spatialviewid=uuid.UUID(view["spatialviewid"]),                                                                                  
          slug=view["slug"],
          schema="public",                                                                                                              
          description=view["description"],
          geometrynode=Node.objects.get(pk=uuid.UUID(view["geometry_node_id"])),
          language=language,                                                                                                            
          ismixedgeometrytypes=view.get("ismixedgeometrytypes", False),
          isactive=True,                                                                                                                
          attributenodes=view["attributenodes"],
      )                                                                                                                                 
   
                                                                                                                                            
def delete_spatial_views(apps, schema_editor):
  SpatialView = apps.get_model("models", "SpatialView")
  slugs = [
      json.loads(p.read_text())["slug"]
      for p in SPATIAL_VIEWS_DIR.glob("*.json")                                                                                         
  ]
  SpatialView.objects.filter(slug__in=slugs).delete()    

class Migration(migrations.Migration):
    dependencies = [
        ("models", "10705_spatialviews_internationalisation_support"),
    ]

    operations = [
        migrations.RunPython(create_spatial_views, delete_spatial_views),
    ]                                                                                                                                     

